"""add_nutritional_info_to_recipes

Revision ID: 0001
Revises:
Create Date: YYYY-MM-DD HH:MM:SS.ffffff

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None # Assuming this is the first migration, or should be linked to a previous one.
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('calories', sa.Numeric(10, 2), nullable=True))
    op.add_column('recipes', sa.Column('protein', sa.Numeric(10, 2), nullable=True))
    op.add_column('recipes', sa.Column('carbohydrates', sa.Numeric(10, 2), nullable=True))
    op.add_column('recipes', sa.Column('fat', sa.Numeric(10, 2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'fat')
    op.drop_column('recipes', 'carbohydrates')
    op.drop_column('recipes', 'protein')
    op.drop_column('recipes', 'calories')
    # ### end Alembic commands ###
